# Source: https://github.com/draios/sysdig-cloud-scripts/blob/master/agent_deploy/kubernetes/sysdig-benchmark-runner-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-benchmark-runner
data:
  debug: "false"

  # Set and customize the following to enable proxy support
  # http_proxy: "http://proxy_server:8080"
  # https_proxy: "https://proxy_server:8080"
  # no_proxy: "127.0.0.1,localhost,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"

  # The endpoint to the Sysdig collector
  # Required: yes
  collector_endpoint: ingest.eu-de.monitoring.cloud.ibm.com
